### ISSUE TITLE
Intermittent errors with Google Cloud TTS and Chinese (UPDATE: VPN causes 403 errors)

### ISSUE THREAD

**Issue by brownbat** [AwesomeTTS/awesometts-anki-addon#153]
On latest, ATTS v1.27 and Anki 2.1.35.

I have the following cloze field on the frontside, with settings selected to only play what's visible:
公司 [...] 大。

When reaching this card I consistently get the following error:

---------------------------
Anki
---------------------------
AwesomeTTS: Could not play back 公司 大 。: None of the presets in this group were able to play the input text.
---------------------------
OK   
---------------------------

My preset group "Chinese" contains all Wavenet voices for Taiwan ("cmn-TW-Wavenet-A", /B/C/D) and mainland China ("cmn-CN-Wavenet-A", +B-D).

Testing I've done so far:
- I made a toy program in python to call Google TTS with this input, and it correctly responds using any voice in the preset.
- Removed the TTS field in the card and re-added it through the ATTS buttons, to ensure the language was correctly mapped for that deck.

I'm going to see if I can get a sense of which cards this affects, so far have just seen it on two cloze cards. 

Let me know if there's any other info I can provide or anything else to check.

**Comment by brownbat** [comment]
Hmm, this isn't even a cloze card, just a simple character: 

![image](https://user-images.githubusercontent.com/26754/99838797-ad8fa500-2b37-11eb-94ea-286ff203cd5e.png)

**Comment by brownbat** [comment]
Hmm, this isn't even a cloze card, just a simple character: 

![image](https://user-images.githubusercontent.com/26754/99838797-ad8fa500-2b37-11eb-94ea-286ff203cd5e.png)

Other tests:

Working correctly:
廣
牠
還
幫
美
兒 (儿)

Breaks:
了

So far no clear pattern. Some of the working characters are traditional Chinese characters, some are simplified.

**Comment by brownbat** [comment]
Ok, another weird correlation -- seems to break more often when I'm using a VPN. But even then, only in Anki, not in my Python script. 

Maybe some combination of IP address and the way ATTS sends requests causes Google to drop the request because it looks fishy. Here's how I'm composing requests, curious how different your requests will look from these:

```python
import os, string, sys
from google.cloud import texttospeech

# <<set CREDS_FILE_LOCATION here>>
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = CREDS_FILE_LOCATION

def hanzi_to_mp3(hanzi, out_filename = None):
    # <<handle default filename generation here>>
    client = texttospeech.TextToSpeechClient()
    synthesis_input = texttospeech.types.SynthesisInput(text=hanzi)
    voice_name = "cmn-TW-Wavenet-A"  # cmn-CN-Wavenet-C, etc.
    voice = texttospeech.types.VoiceSelectionParams(
        language_code='zh-CN',
        name=voice_name)
    audio_config = texttospeech.types.AudioConfig(
        audio_encoding=texttospeech.enums.AudioEncoding.MP3, #OGG_OPUS,
        pitch=1,
        speaking_rate=1)
    response = client.synthesize_speech(synthesis_input, voice, audio_config)

    with open(out_filename, 'wb') as out:
        out.write(response.audio_content)
        print('Audio content written to file "',out_filename,'"', sep='')

hanzi_to_mp3("公司 大。")

```

**Comment by lucwastiaux** [comment]
Are you familiar with environment variables ? Could you try running this experiment in Anki with  AWESOMETTS_DEBUG_LOGGING=enable set ? it will print a lot of useful debugging info to the console which we can use to track down the problem.

**Comment by brownbat** [comment]
I just hardcoded logging to on for a session:
```python
#if 'AWESOMETTS_DEBUG_LOGGING' in os.environ and os.environ['AWESOMETTS_DEBUG_LOGGING'] == 'enable':
if True:
```

But hit some UnicodeErrors before I could do much testing unfortunately.


```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-20 09:43:12

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u5b9a' in position 97: character maps to <undefined>
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 238, in <lambda>
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 56, in _play
    self._addon.logger.debug(f"playing back for language {language}, text: {tag.field_text}")
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'playing back for language zh_CN, text: 定'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u5b9a' in position 280: character maps to <undefined>
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 238, in <lambda>
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 81, in _play
    text = self._addon.strip.from_template(text)
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 128, in __call__
    self._log(applied, text)
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 135, in _log
    self._logger.debug("Transformation using %s: %s", method,
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Transformation using %s: %s'
Arguments: ([('clozes_rendered', 'ellipsize'), 'hint_links', 'html', 'whitespace', 'sounds_univ', 'filenames', 'within_parens', 'within_brackets', 'within_braces', ('char_remove', '*'), 'ellipses', 'whitespace'], '定')
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u5b9a' in position 103: character maps to <undefined>
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 238, in <lambda>
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 107, in _play
    self._addon.logger.info(f"playing back text with group: {group_name}, text: {text}.")
  File "logging\__init__.py", line 1434, in info
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'playing back text with group: Chinese, text: 定.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u5b9a' in position 177: character maps to <undefined>
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 238, in <lambda>
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 117, in _play
    self._addon.router.group(
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 332, in group
    try_next()
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 328, in try_next
    self(svc_id=svc_id, text=text, options=preset,
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 402, in __call__
    self._logger.debug(
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Parsed call to \'%s\' w/ %s and "%s" at %s (cache %s)'
Arguments: ('googletts', {'voice': 'cmn-TW-Wavenet-A', 'speed': 1.0, 'pitch': 0.0, 'profile': 'default'}, '定', 'C:\\Users\\...\\AppData\\Roaming\\Anki2\\addons21\\1436550454\\awesometts\\.cache\\googletts-addf2435-c80c56ff-b45e3fd0-ee760098-9605d72d.mp3', 'hit')
```

**Comment by lucwastiaux** [comment]
Can you send me your deck, and tell me which cards cause both the logging problem and the playback issue ?

**Comment by brownbat** [comment]
[ATTS test deck.apkg.zip](https://github.com/AwesomeTTS/awesometts-anki-addon/files/5578749/ATTS.test.deck.apkg.zip)

1. Just rename to remove the extension.
2. 定 "set a date" caused the UnicodeError
3. If I (a) use a VPN, and (b) use on the fly playback, to (c) play the "Expression" field, that (d) I have not yet cached, it reliably bugs. If I'm highlighting the text from the browser and trigger ATTS from the context menu item "Say x w/ voice..." then it just silently fails. If it's on a card it gives me the error above.

Pretty sure that since I can only get this to persist when I'm using a VPN it's on Google's end. You may still want to look into the Unicode error for logging as an independent issue though.

Thanks for taking a look, good luck.

**Comment by lucwastiaux** [comment]
Question: why does C:\python38 appear in the log file above ? Are you not using a standard Anki install ?

**Comment by brownbat** [comment]
> Question: why does C:\python38 appear in the log file above ? Are you not using a standard Anki install ?

Standard installer. Which version of python does 2.1.35 package? 

Anki's Windows installer might just check to see if Python is already installed and uses the latest version?

**Comment by brownbat** [comment]
![image](https://user-images.githubusercontent.com/26754/99908810-bbb60080-2cb2-11eb-86b3-0f0ea7af26d0.png)

**Comment by lucwastiaux** [comment]
Question: is batch generation an option for you ? It would give you the advantage of being able to use the audio on mobile apps. I'm not able to reproduce the issue, I can pronounce 定 using on-the-fly TTS and a google wavenet voice.

**Comment by lucwastiaux** [comment]
I've updated the debug logging procedures, on windows, debug logging is now done to a file: https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging
please follow these instructions, then attempt to play audio again. Then, post the debug log file here.

**Comment by brownbat** [comment]
This is a really useful debug model! Unfortunately I hit a snag...

![image](https://user-images.githubusercontent.com/26754/103461251-f1ef9280-4cea-11eb-8507-cb25dd0a8be2.png)

1. I checked for awesometts.log in %TEMP% after the error, while Anki was open, it didn't exist.
2. I checked for it after closing Anki, in case you're flushing logs at the end (unlikely). It didn't exist.
3. I created awesometts.log in advance and repeated the above steps, in case it was failing to create a file, but nothing was written to it.
4. I repeated all the above steps in an Admin window, in case there were insufficient permissions to write to temp (unlikely), but nothing was written to the file.
5. I searched for other log files in temp directories that had been recently updated, but couldn't find a good candidate. I can't conclusively rule out that it was written somewhere else, but I couldn't find it after a quick search for any files <130 kb on C:\ that were modified within the last 5 minutes.

For the main bug, sorry for not replying sooner. It only seems to happen when I'm using a VPN. Which suggests to me that it's most likely Google detecting VPNs, then sending 403s to prevent abuse. Which means... it's not likely to be fixable, and I just need to remember to turn off the VPN when I do reps. Not a hard workaround.

Still happy to send logs once I can collect them if that's helpful, thanks for your persistent improvements to this program and attention to all issues.

**Comment by lucwastiaux** [comment]
set AWESOMETTS_DEBUG_LOGGING=file

It must be set to "file"

**Comment by brownbat** [comment]
Ah, sorry for missing that.
```
20210102-21:20:16,822 DEBUG    [config.py:64] Executing 'SELECT name FROM sqlite_master WHERE type=? AND name=?' with ('table', 'general')
20210102-21:20:16,823 DEBUG    [config.py:67] Executing 'PRAGMA table_info(general)'
20210102-21:20:16,823 DEBUG    [config.py:67] Executing 'SELECT * FROM general'
20210102-21:20:43,965 DEBUG    [router.py:388] Call for 'googletts' w/ {'voice': 'cmn-TW-Wavenet-C', 'speed': 1.0, 'pitch': 0.0, 'profile': 'default'}
20210102-21:20:43,965 INFO     [router.py:837] Initializing Google Cloud Text-to-Speech service...
20210102-21:20:43,965 INFO     [router.py:845] Google Cloud Text-to-Speech service initialized
20210102-21:20:43,966 DEBUG    [router.py:730] Building the options list for Google Cloud Text-to-Speech
20210102-21:20:43,966 DEBUG    [router.py:774] Building the extras list for Google Cloud Text-to-Speech
20210102-21:20:43,966 DEBUG    [router.py:696] Validated and normalized 'voice', 'speed', 'pitch', 'profile' with failure count of 0
20210102-21:20:43,968 DEBUG    [router.py:938] Spawned thread [1]; pool={1: {'callback': <function Router.__call__.<locals>.completion_callback at 0x0000017F7BAE8F70>, 'done': False, 'worker': <1436550454.awesometts.router._Worker object at 0x0000017F7A8FC040>}}
20210102-21:20:43,971 DEBUG    [connectionpool.py:955] Starting new HTTPS connection (1): texttospeech.googleapis.com:443
20210102-21:20:44,599 DEBUG    [connectionpool.py:428] https://texttospeech.googleapis.com:443 "POST /v1/text:synthesize?key=<my-api-key> HTTP/1.1" 200 None
20210102-21:20:44,621 DEBUG    [router.py:965] Completion from thread [1]; executing callback
20210102-21:20:44,622 DEBUG    [ttsplayer.py:140] done playing
20210102-21:20:44,622 DEBUG    [router.py:992] Reaped thread [1]; pool={}
20210102-21:23:10,344 DEBUG    [router.py:388] Call for 'googletts' w/ {'voice': 'cmn-CN-Wavenet-A', 'speed': 1.0, 'pitch': 0.0, 'profile': 'default'}
20210102-21:23:10,344 DEBUG    [router.py:696] Validated and normalized 'voice', 'speed', 'pitch', 'profile' with failure count of 0
20210102-21:23:10,346 DEBUG    [router.py:938] Spawned thread [2]; pool={2: {'callback': <function Router.__call__.<locals>.completion_callback at 0x0000017F00A29940>, 'done': False, 'worker': <1436550454.awesometts.router._Worker object at 0x0000017F7A8FC040>}}
20210102-21:23:10,347 DEBUG    [connectionpool.py:955] Starting new HTTPS connection (1): texttospeech.googleapis.com:443
20210102-21:23:10,463 DEBUG    [connectionpool.py:428] https://texttospeech.googleapis.com:443 "POST /v1/text:synthesize?key=<my-api-key> HTTP/1.1" 403 None
20210102-21:23:10,477 DEBUG    [router.py:954] Exception from thread [2] (403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=<my-api-key>); executing callback
!!! Traceback (most recent call last):
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 1028, in run
!!!     self._task()
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 558, in task
!!!     service['instance'].run(text, options, path)
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\service\googletts.py", line 385, in run
!!!     r.raise_for_status()
!!!   File "requests\models.py", line 940, in raise_for_status
!!! requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=<my-api-key>
!!! 
20210102-21:23:10,477 DEBUG    [router.py:388] Call for 'googletts' w/ {'voice': 'cmn-CN-Wavenet-C', 'speed': 1.0, 'pitch': 0.0, 'profile': 'default'}
20210102-21:23:10,477 DEBUG    [router.py:696] Validated and normalized 'voice', 'speed', 'pitch', 'profile' with failure count of 0
20210102-21:23:10,479 DEBUG    [router.py:938] Spawned thread [3]; pool={2: {'callback': <function Router.__call__.<locals>.completion_callback at 0x0000017F00A29940>, 'done': False, 'worker': <1436550454.awesometts.router._Worker object at 0x0000017F7A8FC040>}, 3: {'callback': <function Router.__call__.<locals>.completion_callback at 0x0000017F7BB479D0>, 'done': False, 'worker': <1436550454.awesometts.router._Worker object at 0x0000017F7A7D4360>}}
20210102-21:23:10,480 DEBUG    [router.py:992] Reaped thread [2]; pool={3: {'callback': <function Router.__call__.<locals>.completion_callback at 0x0000017F7BB479D0>, 'done': False, 'worker': <1436550454.awesometts.router._Worker object at 0x0000017F7A7D4360>}}
20210102-21:23:10,482 DEBUG    [connectionpool.py:955] Starting new HTTPS connection (1): texttospeech.googleapis.com:443
20210102-21:23:10,592 DEBUG    [connectionpool.py:428] https://texttospeech.googleapis.com:443 "POST /v1/text:synthesize?key=<my-api-key> HTTP/1.1" 403 None
20210102-21:23:10,594 DEBUG    [router.py:954] Exception from thread [3] (403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=<my-api-key>); executing callback
!!! Traceback (most recent call last):
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 1028, in run
!!!     self._task()
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 558, in task
!!!     service['instance'].run(text, options, path)
!!!   File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\service\googletts.py", line 385, in run
!!!     r.raise_for_status()
!!!   File "requests\models.py", line 940, in raise_for_status
!!! requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=<my-api-key>
!!! 
```

Then that last bit, from router.py:388 to the end, repeats like 20 or 30 times. I also received a Unicode error in logging, maybe that's a separate report.

**Comment by brownbat** [comment]
The separate logging error, let me know if you want me to file this under a different issue: 

```
Message: 'playing back text with group: Chinese, text: 自己的事情自己做。.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 162-170: character maps to <undefined>
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 238, in <lambda>
  File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 117, in _play
    self._addon.router.group(
  File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 332, in group
    try_next()
  File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 328, in try_next
    self(svc_id=svc_id, text=text, options=preset,
  File "C:\Users\thomas\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 402, in __call__
    self._logger.debug(
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Parsed call to \'%s\' w/ %s and "%s" at %s (cache %s)'
Arguments: ('googletts', {'voice': 'cmn-TW-Wavenet-C', 'speed': 1.0, 'pitch': 0.0, 'profile': 'default'}, '自己的事情自己做。', 'C:\\Users\\thomas\\AppData\\Roaming\\Anki2\\addons21\\1436550454\\awesometts\\.cache\\googletts-085d9(...).mp3', 'miss')
```

**Comment by lucwastiaux** [comment]
Your deck doesn't seem to have cloze deletions given the sample you posted. Given this, why don't you use batch generation ? That way, you don't need to be online when you're reviewing.

**Comment by brownbat** [comment]
You've recommended that before, I considered it for a while, but still haven't made the leap to pre-gen for a few reasons.

Some of my other decks do use cloze, but mainly I prefer on the fly generation because I have such a large combination of possible voices and cards. On the fly lets me spread out my use of the API key and save my local storage from being filled with combinations I'll never need. I could probably calculate it out and do batches of the next hundred cards at a time or so, but that seems a lot more fiddly than just doing new cards as they come up.

Sorry, all of us stubbornly addicted to on the fly probably makes the design model more complicated; but it really is a great feature for us, really does save us a lot of hassle in one way or another.

**Comment by lucwastiaux** [comment]
No worries, on-the-fly TTS will continue to be supported, after all it's a default feature in Anki now (though you need AwesomeTTS for the premium voices).

**Comment by brownbat** [comment]
Based on the comments on #196 I consider this one solved, required going to my Google Cloud dashboard and changing restrictions on my API key, as discussed in this other project: 
https://github.com/changemyminds/Google-Cloud-TTS-Android/issues/1
