### ISSUE TITLE
Naver Clova freezing without fail. 

### ISSUE THREAD

**Issue by michaelcward1996** [AwesomeTTS/awesometts-anki-addon#166]
![image](https://user-images.githubusercontent.com/33991266/103435199-4c400480-4bc0-11eb-80c5-5346fcf66ac3.png)
After (usually about 10 or so) mp3s have been generated Anki freezes requiring a task manager reboot.

**Comment by lucwastiaux** [comment]
Can you try to enable debug logging as described here: https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging , then attempt to generate naver clova audio, and paste the log file here ?

**Comment by michaelcward1996** [comment]
This error came up when I tried to run anki in the manner listed. This error popped up several times, I'm guessing one for each TTS generation attempt. However no debug file was created in the temp folder.
With each error report the "171-172"part below changed a little bit, ranging from 171-176. It seemed like all the other text was the same between the errors. 
UnicodeEncodeError: 'charmap' codec can't encode characters in position **171-172:** character maps to <undefined>


Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-01 20:46:28

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 171-172: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 400, in run
  File "aqt\__init__.py", line 570, in _run
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 336, in _accept_next
    phrase = self._addon.strip.from_note(phrase)
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 128, in __call__
    self._log(applied, text)
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 135, in _log
    self._logger.debug("Transformation using %s: %s", method,
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Transformation using %s: %s'
Arguments: ([('clozes_braced', 'anki'), 'html', 'whitespace', 'sounds_univ', 'filenames', 'ellipses', 'whitespace'], '건강 프로그램에 참여를 원하시는 분들은 빨리 신청하세요.')
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 114-115: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 400, in run
  File "aqt\__init__.py", line 570, in _run
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "aqt\errors.py", line 115, in onTimeout
  File "aqt\utils.py", line 163, in showText
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 399, in _accept_next
    self._addon.router(svc_id=svc_id,
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 402, in __call__
    self._logger.debug(
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Parsed call to \'%s\' w/ %s and "%s" at %s (cache %s)'
Arguments: ('naverclova', {'voice': 'jinho', 'speed': 0}, '건강 프로그램에 참여를 원하시는 분들은 빨리 신청하세요.', 'C:\\Users\\micha\\AppData\\Roaming\\Anki2\\addons21\\1436550454\\awesometts\\.cache\\naverclova-1373cb66-79098677-9320a904-1f180f0b-722a1736.mp3', 'miss')

**Comment by michaelcward1996** [comment]
I did test this with all of my addons disabled except for AwesomeTTS by the way and I had the same result. Anyway happy hunting. This addon  has been enormously helpful (even with just the 50 or so audio files I have been able to generate). So yea, thanks :)

**Comment by lucwastiaux** [comment]
Can you share your deck, and give me a sample selection of cards which produces the issue ?

**Comment by michaelcward1996** [comment]
AwesomeTTS usually freezes somewhere between 10 and 20 cards, so usually any sample of cards that is higher than that ends up freezing. Here is the example deck. 
[Selected Notes.zip](https://github.com/AwesomeTTS/awesometts-anki-addon/files/5760109/Selected.Notes.zip)

**Comment by lucwastiaux** [comment]
OK so I made a little bit of progress in understanding what is happening. When I asked you to enable debug logging, this triggered another bug, related to character encoding and which only happens on windows. I will try to solve that problem first, because unless I solve that, I don't think i'll be able to get to the bottom of your freezing problem.

```

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 174-175: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 400, in run
  File "aqt\__init__.py", line 570, in _run
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 298, in accept
    self._accept_next()
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 336, in _accept_next
    phrase = self._addon.strip.from_note(phrase)
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 128, in __call__
    self._log(applied, text)
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py", line 135, in _log
    self._logger.debug("Transformation using %s: %s", method,
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Transformation using %s: %s'
Arguments: ([('clozes_braced', 'deleted'), 'html', 'whitespace', 'sounds_univ', 'filenames', 'ellipses', 'whitespace'], '건강 프로그램에 참여를 원하시는 분들은 빨리 신청하세요.')
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 114-115: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 400, in run
  File "aqt\__init__.py", line 570, in _run
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 298, in accept
    self._accept_next()
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 399, in _accept_next
    self._addon.router(svc_id=svc_id,
  File "C:\Users\lucwa\AppData\Roaming\Anki2\addons21\1436550454\awesometts\router.py", line 402, in __call__
    self._logger.debug(
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'Parsed call to \'%s\' w/ %s and "%s" at %s (cache %s)'
Arguments: ('naverclova', {'voice': 'jinho', 'speed': 0}, '건강 프로그램에 참여를 원하시는 분들은 빨리 신청하세요.', 'C:\\Users\\lucwa\\AppData\\Roaming\\Anki2\\addons21\\1436550454\\awesometts\\.cache\\naverclova-1373cb66-79098677-9320a904-1f180f0b-722a1736.mp3', 'miss')
```

**Comment by michaelcward1996** [comment]
Freezing no longer happens, I'm guessing it was somehow fixed as part of TTS premium. Thanks!

**Comment by lucwastiaux** [comment]
ah good to hear !
