### ISSUE TITLE
Error on audio card

### ISSUE THREAD

**Issue by masonc15** [AwesomeTTS/awesometts-anki-addon#179]
Hello,

I recently got Premium AwesomeTTS through Patreon and I'm having an error.  It's really weird because these cards were working initially quite well but when I tried again, I get an error when flipping to the back side.  I get the following error:

```
Debug info:
Anki 2.1.39 (576f0043) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-10 21:07:17

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 87, in _on_closures_pending
  File "aqt\taskman.py", line 59, in <lambda>
  File "aqt\sound.py", line 279, in <lambda>
  File "C:\Users\Colin\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 146, in _on_done
    ret.result()
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\sound.py", line 279, in <lambda>
  File "C:\Users\Colin\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 90, in _play
    preset = self._addon.config['presets'][awesometts_preset_name]
KeyError: 'Microsoft Azure (Microsoft Server Speech Text to Speech Voice (ja-JP, NanamiNeural))'
```

Any help would be appreciated.  Thank you.

**Comment by lucwastiaux** [comment]
Hi, could you try re-adding the TTS tag in your card template ? I'm not completely sure what happened but it looks like your preset is missing.

**Comment by masonc15** [comment]
I re-added it but now I'm not able to hear anything in the Preview when I'm adding the TTS tag.  The card flip doesn't spit out an error but the audio doesn't play anything.

**Comment by masonc15** [comment]
Update: I re-installed the addon from scratch and created a new preset.  Working fine now.  Really unsure what happened.  I also restarted Anki after setting it and everything is good.  Hopefully the error doesn't pop up again.

**Comment by lucwastiaux** [comment]
Glad it's working for you. I believe just creating a new preset would have been enough. Don't hesitate to let me know if you run into any other issues.
