### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sousaakira** [AwesomeTTS/awesometts-anki-addon#244]
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (e42dccf8) Python 3.9.7 Qt 6.2.1 PyQt 6.2.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-01-03 02:19:44
Add-ons possibly involved: ⁨AwesomeTTS⁩

Caught exception:
Traceback (most recent call last):
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 76, in __init__
    super(Configurator, self).__init__(title="Configuration",
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 85, in _ui
    layout.addWidget(self._ui_tabs())
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 103, in _ui_tabs
    tabs.addTab(content(), QtGui.QIcon(f'{ICONS}/{icon}.png'),
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 118, in _ui_tabs_text
    layout.addWidget(self._ui_tabs_text_mode(
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 152, in _ui_tabs_text_mode
    ("Advanced", self._ui_tabs_text_mode_adv(infix)),
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/configurator.py", line 287, in _ui_tabs_text_mode_adv
    return Slate("Rule", SubListView, [self._sul_compiler],
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/common.py", line 307, in __init__
    list_view = ListViewClass(*list_view_args)
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/listviews.py", line 115, in __init__
    super(SubListView, self).__init__(*args, **kwargs)
  File "/home/akira/.local/share/Anki2/addons21/awesometts/awesometts/gui/listviews.py", line 50, in __init__
    self.setSelectionMode(self.ExtendedSelection)
AttributeError: 'SubListView' object has no attribute 'ExtendedSelection'

**Comment by lucwastiaux** [comment]
Hi, can you share a bit more details on what happened before this crash ?
