### ISSUE TITLE
AttributeError: module 'PyQt6' has no attribute 'QtWidgets'  (anki 2.1.51)

### ISSUE THREAD

**Issue by mkurmag** [AwesomeTTS/awesometts-anki-addon#263]
Got error message on anki 2.1.51:
```
When loading '⁨AwesomeTTS - Add speech to your flashcards⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/__init__.py", line 42, in <module>
    from . import awesometts  # noqa, pylint:disable=wrong-import-position
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/awesometts/__init__.py", line 32, in <module>
    from . import conversion as to, gui, paths, service
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/awesometts/gui/__init__.py", line 31, in <module>
    from .configurator import Configurator
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/awesometts/gui/configurator.py", line 30, in <module>
    from .base import Dialog
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/awesometts/gui/base.py", line 192, in <module>
    class ServiceDialog(Dialog):
  File "/home/kurban/.local/share/Anki2/addons21/1436550454/awesometts/gui/base.py", line 198, in ServiceDialog
    _OPTIONS_WIDGETS = (PyQt6.QtWidgets.QComboBox, aqt.qt.QDoubleSpinBox, aqt.qt.QSpinBox)
AttributeError: module 'PyQt6' has no attribute 'QtWidgets'
```

Replacing `import PyQt6` with `import PyQt6.QtWidgets` in awesometts/gui/base.py fixes the issue.

**Comment by luc-languagetools** [comment]
Fixed in AwesomeTTS 1.62
