### ISSUE TITLE
 unable to set shortcuts in AwesomeTTS

### ISSUE THREAD

**Issue by luc-languagetools** [AwesomeTTS/awesometts-anki-addon#283]
this has been reported by a number of people

Add-ons possibly involved: ⁨AwesomeTTS - Add speech to your flashcards⁩  Caught exception: Traceback (most recent call last):   File "/home/kasm-user/.local/share/Anki2/addons21/1436550454/awesometts/gui/configurator.py", line 710, in keyPressEvent     combo = key_event_combo(key_event)   File "/home/kasm-user/.local/share/Anki2/addons21/1436550454/awesometts/gui/common.py", line 62, in key_event_combo     return key + sum(flag TypeError: unsupported operand type(s) for +: 'int' and 
'KeyboardModifier'

including August over email

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\configurator.py", line 710, in keyPressEvent
    combo = key_event_combo(key_event)
  File "C:\Users\user \AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\common.py", line 62, in key_event_combo
    return key + sum(flag
TypeError: unsupported operand type(s) for +: 'int' and 'KeyboardModifier'

**Comment by luc-languagetools** [comment]
should be fixed in upcoming version

**Comment by luc-languagetools** [comment]
Fixed in 1.74.
