### ISSUE TITLE
Anki QT5 2.1.60 incompatabilty 

### ISSUE THREAD

**Issue by fen93t** [AwesomeTTS/awesometts-anki-addon#287]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-22 08:52:30

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 604, in handler
  File "aqt.reviewer", line 641, in _onTypedAnswer
  File "aqt.reviewer", line 409, in _showAnswer
  File "aqt.sound", line 150, in play_tags
  File "aqt.sound", line 209, in _play_next_if_idle
  File "aqt.sound", line 212, in _play
  File "aqt.sound", line 223, in _best_player_for_tag
  File "aqt.tts", line 120, in rank_for_tag
  File "aqt.tts", line 85, in voice_for_tag
  File "aqt.tts", line 81, in voices
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1436550454\awesometts\ttsplayer.py", line 41, in get_available_voices
    voices.append(TTSVoice(name="AwesomeTTS", lang=language_name, available=True))
TypeError: __init__() got an unexpected keyword argument 'available'

**Comment by fen93t** [comment]
I can confirm 2.1.58 QT5 works fine.

**Comment by nikita-moor** [comment]
Fixed, confirm.

**Comment by luc-languagetools** [comment]
Latest AwesomeTTS should work.
