### ISSUE TITLE
Error code when trying to use it

### ISSUE THREAD

**Issue by wolfkie** [AwesomeTTS/awesometts-anki-addon#296]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-12 13:14:29

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 662, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 440, in cs_captureBridgeToggleSticky
    return _old(self,cmd)
  File "aqt.editor", line 474, in onBridgeCmd
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\Wolfgang\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'

**Comment by luc-languagetools** [comment]
Please install the official version: https://ankiweb.net/shared/info/1436550454
