### ISSUE TITLE
AwesomeTTS hangs Anki  23.12.1 on MacOS M1

### ISSUE THREAD

**Issue by danieltomasz** [AwesomeTTS/awesometts-anki-addon#312]
Error details
```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/configurator.py", line 282, in validate
    return aqt.qt.QValidator.Acceptable, filtered, len(filtered)
AttributeError: type object 'QValidator' has no attribute 'Acceptable'

Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/configurator.py", line 282, in validate
    return aqt.qt.QValidator.Acceptable, filtered, len(filtered)
AttributeError: type object 'QValidator' has no attribute 'Acceptable'

```

**Comment by ryanlinnane** [comment]
Same issue. Just tried this on a new device M2 after an upgrade.

**Comment by AuroraWright** [comment]
It's a Qt6 issue, not a macOS or M1 issue https://github.com/AwesomeTTS/awesometts-anki-addon/pull/308

**Comment by luc-languagetools** [comment]
which version of AwesomeTTS ?

**Comment by AuroraWright** [comment]
Latest published on ankiweb

**Comment by luc-vocab** [comment]
@danieltomasz  @ryanlinnane @AuroraWright is there anything preventing you from upgrading to HyperTTS ? HyperTTS has almost 99% unit test coverage which prevents issues like these.

**Comment by AuroraWright** [comment]
> @danieltomasz @ryanlinnane @AuroraWright is there anything preventing you from upgrading to HyperTTS ? HyperTTS has almost 99% unit test coverage which prevents issues like these.

I upgraded a month ago or so!

**Comment by luc-vocab** [comment]
great to hear !
