### ISSUE TITLE
Anki 2.1.20beta7 anki.template.template.clozeReg

### ISSUE THREAD

**Issue by khonkhortisan** [AwesomeTTS/awesometts-anki-addon#85]
```
---------------------------
Anki
---------------------------
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'AwesomeTTS Google Cloud Text-to-Speech unofficial':
Traceback (most recent call last):
  File "aqt\addons.py", line 201, in loadAddons
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\814349176\__init__.py", line 42, in <module>
    from . import awesometts  # noqa, pylint:disable=wrong-import-position
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\814349176\awesometts\__init__.py", line 36, in <module>
    from .player import Player
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\814349176\awesometts\player.py", line 25, in <module>
    from .text import RE_FILENAMES
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\814349176\awesometts\text.py", line 32, in <module>
    from anki.template.template import clozeReg
ModuleNotFoundError: No module named 'anki.template.template'; 'anki.template' is not a package


---------------------------
OK   
---------------------------

```
This error message is from an unofficial upload, but the line that throws it remains unchanged, so this issue should be valid.

**Comment by omega3** [comment]
Please update for version 2.1.20

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'AwesomeTTS for Anki 21 updated again':
Traceback (most recent call last):
File "aqt/addons.py", line 205, in loadAddons
File "/home/user/.local/share/Anki2/addons21/2139632824/__init__.py", line 42, in <module>
from . import awesometts # noqa, pylint:disable=wrong-import-position
File "/home/user/.local/share/Anki2/addons21/2139632824/awesometts/__init__.py", line 36, in <module>
from .player import Player
File "/home/user/.local/share/Anki2/addons21/2139632824/awesometts/player.py", line 25, in <module>
from .text import RE_FILENAMES
File "/home/user/.local/share/Anki2/addons21/2139632824/awesometts/text.py", line 35, in <module>
RE_CLOZE_BRACED = re.compile(anki.template.template.clozeReg % r'\d+')
AttributeError: module 'anki.template' has no attribute 'template' 
```
